app:
  gin_mode: "${GIN_MODE}"
http:
  host: "${APP_HOST}"
  port: "${APP_PORT}"
minio:
  endpoint: "${MINIO_ENDPOINT}"
  rootUser: "${MINIO_ROOT_USER}"
  rootPassword: "${MINIO_ROOT_PASSWORD}"
  bucketName: "${MINIO_BUCKET}"