definitions:
  requests.Category:
    properties:
      name:
        type: string
    type: object
  requests.CreateFile:
    type: object
  requests.File:
    properties:
      folder:
        $ref: '#/definitions/requests.Folder'
      name:
        type: string
    type: object
  requests.Folder:
    properties:
      category:
        $ref: '#/definitions/requests.Category'
      name:
        type: string
    type: object
  responses.Category:
    properties:
      folders:
        items:
          $ref: '#/definitions/responses.Folder'
        type: array
      name:
        type: string
      user_id:
        type: string
    type: object
  responses.File:
    properties:
      created_at:
        type: string
      description:
        type: string
      name:
        type: string
      size:
        type: integer
      type:
        type: string
      url:
        type: string
      version:
        type: string
    type: object
  responses.Folder:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /app/account:
    post:
      consumes:
      - application/json
      description: Создает аккаунт для пользователя, с последующем созданием категорий
      parameters:
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат создания
          schema:
            type: string
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Создание аккаунта пользователя
      tags:
      - Account
  /app/categories:
    get:
      consumes:
      - application/json
      description: Возвращает все категории и лежащие в них папки
      parameters:
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Категории данного аккаунта
          schema:
            items:
              $ref: '#/definitions/responses.Category'
            type: array
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получение всех категорий
      tags:
      - Categories
  /app/category:
    get:
      consumes:
      - application/json
      description: Возвращает конкретную категорию и ее папку
      parameters:
      - description: Название категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Category'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Категория данного аккаунта
          schema:
            $ref: '#/definitions/responses.Category'
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получение конкретной категории
      tags:
      - Categories
    post:
      consumes:
      - application/json
      description: Создает категорию для пользователя по ID переданного через токен
      parameters:
      - description: Название категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Category'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат создания
          schema:
            type: string
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Создание категории пользователя
      tags:
      - Categories
  /app/category/delete:
    post:
      consumes:
      - application/json
      description: Удаляет категорию, ее папки и файлы
      parameters:
      - description: Название категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Category'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат удаление
          schema:
            type: string
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Удаление категории
      tags:
      - Categories
  /app/category/exist:
    get:
      consumes:
      - application/json
      description: Проверяет, существует ли категория для указанного аккаунта
      parameters:
      - description: Название категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Category'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат проверки (true - существует, false - не существует)
          schema:
            type: boolean
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Проверка существования категории
      tags:
      - Categories
  /app/file:
    get:
      consumes:
      - application/json
      description: Возвращает файл конкретной категории и папки
      parameters:
      - description: Название файла, папки, категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.File'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Конкретный файл данного аккаунта
          schema:
            $ref: '#/definitions/responses.File'
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получение конкретного файла
      tags:
      - Files
    post:
      consumes:
      - multipart/form-data
      description: Создание и добавление файла в базу данных
      parameters:
      - description: Файл, версия файлы, название папки, название категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.CreateFile'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат создания
          schema:
            type: string
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Добавление файла
      tags:
      - Files
  /app/file/delete:
    post:
      consumes:
      - application/json
      description: Удаляет файл
      parameters:
      - description: Название файла, папки и категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.File'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат удаление
          schema:
            type: string
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Удаление файлы
      tags:
      - Files
  /app/file/exists:
    get:
      consumes:
      - application/json
      description: Проверяет, существует ли файл для указанного аккаунта
      parameters:
      - description: Название файла, папка, категория
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.File'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Результат проверки {\"exists\": true/false}'
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Проверка существования файла
      tags:
      - Files
  /app/files:
    get:
      consumes:
      - application/json
      description: Возвращает все файлы конкретной категории и папки
      parameters:
      - description: Название файла, папки, категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.File'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Файлы в категории и папке данного аккаунта
          schema:
            items:
              $ref: '#/definitions/responses.File'
            type: array
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получение всех файлов
      tags:
      - Files
  /app/folder:
    get:
      consumes:
      - application/json
      description: Возвращает папк конкретной категории
      parameters:
      - description: Название папки, категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Folder'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Конкретная папка данного аккаунта
          schema:
            $ref: '#/definitions/responses.Folder'
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получение нужной папки
      tags:
      - Folders
    post:
      consumes:
      - application/json
      description: Создает папку для пользователя
      parameters:
      - description: Название папки, название категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Folder'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат проверки
          schema:
            type: string
        "400":
          description: Некорректный формат запрос
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Создание папки пользователя
      tags:
      - Folders
  /app/folder/delete:
    post:
      consumes:
      - application/json
      description: Удаляет категорию, ее папки и файлы
      parameters:
      - description: Название папки, категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Folder'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат удаление
          schema:
            type: string
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Удаление папки и лежащие в ней файлы
      tags:
      - Folders
  /app/folder/exist:
    get:
      consumes:
      - application/json
      description: Проверяет, существует ли папка для указанного аккаунта
      parameters:
      - description: Название папки, категория
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Folder'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Результат проверки (true - существует, false - не существует)
          schema:
            type: boolean
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Проверка существования папки
      tags:
      - Folders
  /app/folders:
    get:
      consumes:
      - application/json
      description: Возвращает все папки конкретной категории
      parameters:
      - description: Название папки, категории
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.Folder'
      - description: Токен доступа
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Папки в категории
          schema:
            items:
              $ref: '#/definitions/responses.Folder'
            type: array
        "400":
          description: Некорректный формат запроса
          schema:
            type: string
        "401":
          description: Ошибка аутентификации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получение всех папок
      tags:
      - Folders
swagger: "2.0"
